version: '3.8'

services:
  namenode:
    build: ./hadoop
    container_name: namenode
    ports:
      - "9870:9870" # HDFS UI
      - "9000:9000"
    environment:
      - CLUSTER_NAME=bigdata
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    build: ./hadoop
    container_name: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  hive-metastore:
    build: ./hive
    container_name: hive-metastore
    depends_on:
      - namenode
    environment:
      - HIVE_METASTORE_DB_TYPE=derby

  spark:
    build: ./spark
    container_name: spark
    ports:
      - "4040:4040"
      - "7077:7077"
    depends_on:
      - namenode

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"

volumes:
  hadoop_namenode:
  hadoop_datanode:
