version: '3.8'

services:
  namenode:
    build: ./hadoop
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"  # Web UI do Namenode
      - "9000:9000"  # RPC do HDFS
    environment:
      - CLUSTER_NAME=bigdata
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    build: ./hadoop
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864"  # Web UI do Datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

volumes:
  hadoop_namenode:
  hadoop_datanode:
